spring:
  datasource:
    url: jdbc:postgresql://dpg-cqork7aj1k6c73d7a10g-a.oregon-postgres.render.com:5432/mtz_pgsql
    username: mtz_pgsql_user
    password: wLvgke3ZXeqeQoC5oxC5LCMlzjkF5xoR
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true